name: Enviar e-mail (Gmail)

on:
  workflow_dispatch:   # permite rodar manualmente na aba Actions
  # Descomente abaixo se quiser enviar a cada push na branch main
  # push:
  #   branches: [ "main" ]

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar e-mail via Gmail SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          # Servidor do Gmail
          server_address: smtp.gmail.com
          server_port: 465
          secure: true  # usa SSL (porta 465). Alternativa: 587 com secure: false

          # Credenciais
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}

          # E-mail
          subject: "Teste GitHub Actions"
          to: "cleitonjunior1@gmail.com"
          from: "Cleiton Ribeiro <${{ secrets.GMAIL_USERNAME }}>"
          body: "funcionou"
          # Opcional:
          # content_type: text/plain; charset=utf-8
          # reply_to: ${{ secrets.GMAIL_USERNAME }}
